# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VponDFPSampleSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VponDFPSampleSwift

  pod 'Google-Mobile-Ads-SDK'
  pod 'AdMobMediationAdapterVpadn', '~> 2.0.1'
  pod 'VpadnSDK', '~> 5.1.1'

end
