# Uncomment the next line to define a global platform for your project

# platform :ios, '9.0'

target 'VponAdmobSampleObjC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for VponAdmobSampleObjC

  pod 'Google-Mobile-Ads-SDK', '~> 7.47.0'
  pod 'AdMobMediationAdapterVpadn'
  pod 'VpadnSDK'

end
