# Uncomment the next line to define a global platform for your project

platform :ios, '11.0'

target 'VponAdmobSampleObjC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for VponAdmobSampleObjC

  pod 'Google-Mobile-Ads-SDK', '~> 10.14.0'
  pod 'AdMobMediationAdapterVpadn'
  pod 'VpadnSDK', '~> 5.6.0'

end
