# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VponDFPSampleObjC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for VponDFPSampleObjC

  pod 'Google-Mobile-Ads-SDK'
  pod 'AdMobMediationAdapterVpadn', '~> 2.0.1'
  pod 'VpadnSDK', '~> 5.1.1'

end
