# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VponMopubSampleObjC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for VponMopubSampleObjC

  pod 'mopub-ios-sdk'
  pod 'VpadnSDK', '~> 4.9.3'

end
