# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VponAdmobSampleSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VponAdmobSampleSwift

  pod 'Google-Mobile-Ads-SDK'
  pod 'AdMobMediationAdapterVpadn', '~> 2.0.5'
  pod 'VpadnSDK', '~> 5.2.0'

end
