# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'VponAdmobSampleSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VponAdmobSampleSwift

  pod 'Google-Mobile-Ads-SDK', '~> 10.14.0'
  pod 'AdMobMediationAdapterVpadn'
  pod 'VpadnSDK', '~> 5.6.0'

end
