# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

# 主 Target (使用 SPM)，這裡必須保持空白
target 'VponAdmobSampleSwift' do
  use_frameworks!
  # 這裡不要放任何 pod

end

target 'VponAdmobSampleSwiftPods' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VponAdmobSampleSwift

  pod 'Google-Mobile-Ads-SDK', '~> 12.0'
  pod 'AdMobMediationAdapterVpadn', '2.2.0'
  pod 'VpadnSDK', '~> 5.8.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
